package no.vibrantfounder.bachelor.marketing.api.dto;

import no.vibrantfounder.bachelor.marketing.domain.enums.ContentFormat;
import no.vibrantfounder.bachelor.marketing.domain.enums.Platform;

import java.util.List;

/**
 * DTO representing a platform-specific marketing strategy
 * generated by the AI decision support system.
 */
public record PlatformPlanDto(
        Platform platform,
        String rationale,
        int frequencyPerWeek,
        List<ContentFormat> formats,
        List<ContentPillarDto> contentPillars,
        List<String> hooks,
        List<String> ctaExamples
) {
}
