CREATE TABLE marketing_plan (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                industry VARCHAR(255),
                                target_audience VARCHAR(255),
                                primary_goal VARCHAR(255),
                                resources_per_week INTEGER NOT NULL,
                                raw_json CLOB,
                                generated_at TIMESTAMP
);

CREATE TABLE platform_plan (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               platform VARCHAR(255),
                               frequency_per_week INTEGER NOT NULL,
                               rationale VARCHAR(2000),
                               marketing_plan_id BIGINT NOT NULL,
                               CONSTRAINT fk_platform_plan_marketing_plan
                                   FOREIGN KEY (marketing_plan_id) REFERENCES marketing_plan(id)
                                       ON DELETE CASCADE
);

CREATE TABLE assumption (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            text VARCHAR(2000),
                            risk_level VARCHAR(255),
                            how_to_test VARCHAR(2000),
                            marketing_plan_id BIGINT NOT NULL,
                            CONSTRAINT fk_assumption_marketing_plan
                                FOREIGN KEY (marketing_plan_id) REFERENCES marketing_plan(id)
                                    ON DELETE CASCADE
);

CREATE INDEX idx_marketing_plan_generated_at ON marketing_plan(generated_at);
CREATE INDEX idx_marketing_plan_industry ON marketing_plan(industry);
CREATE INDEX idx_marketing_plan_primary_goal ON marketing_plan(primary_goal);

CREATE INDEX idx_platform_plan_marketing_plan_id ON platform_plan(marketing_plan_id);
CREATE INDEX idx_assumption_marketing_plan_id ON assumption(marketing_plan_id);
